spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tul-shopping-cart
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

value-divider: 2

logging:
  level:
    root: info
server:
  port: 8080
